### ISSUE TITLE
feat: paid query flow

### ISSUE THREAD

**Issue by hopeyen** [graphops/indexer-service-rs#10]
Add the paid query flow into `subgraph_queries\id\:id` to enable profitable data services 🥳.
- `QueryProcessor::execute_paid_query` (might be a plant first)

inherited from @aasseman https://github.com/hopeyen/indexer-service-rs/issues/20

**Comment by aasseman** [comment]
Partial implementation in #24

**Comment by aasseman** [comment]
Finished the primary paid query flow of the indexer-service in #47
