### ISSUE TITLE
feat: Limit indexing status API

### ISSUE THREAD

**Issue by hopeyen** [graphops/indexer-service-rs#6]
For `statusSever`,
1. extract graphql query from the received request
2. filter the query for supported root fields, 
  ```
  let supported_root_fields = [
  "indexingStatuses",
  "publicProofsOfIndexing",
  "entityChangesInBlock",
  "blockData",
  "cachedEthereumCalls",
  "subgraphFeatures",
  "apiVersions",
  ];
  ```
3. send the updated query request to `graph_node_status_endpoint`
4. return the response from graph node

**Comment by ShivangRawat30** [comment]
Hey I am currently learning rust, as it is a good first issue can you please assign this to me

**Comment by hopeyen** [comment]
Hey @ShivangRawat30 contributions are very much welcomed! Please feel free to open a PR

**Comment by hopeyen** [comment]
Hi @ShivangRawat30 please let us know if you are working on this. While we appreciate the gesture to contribute, we will reassign this issue in 2 weeks to make sure this gets resolved within a timely manner

**Comment by ShivangRawat30** [comment]
@hopeyen I am sorry for the delay, I won't be able to work on this issue for now because of some health issues, please assign it to someone else.

**Comment by hopeyen** [comment]
no worries @ShivangRawat30  thanks for the intent, wishing you well
