### ISSUE TITLE
panic on subgraph query

### ISSUE THREAD

**Issue by Theodus** [graphops/indexer-service-rs#61]
Subgraph queries panic early when attempting to use the `QUERY_DURATION` metric.
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: InconsistentCardinality { expect: 2, got: 1 }', /home/theodus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/prometheus-0.13.3/src/vec.rs:258:49
...
at /home/theodus/src/edgeandnode/local-network/build/graphops/indexer-service-rs/service/src/server/routes/subgraphs.rs:40:32
```
`QUERY_DURATION` is declared with the expectation of 2 labels, `deployment` & `name`, [here](https://github.com/graphops/indexer-service-rs/blob/cf21797abf63d9f0b02cf4af9ac61cc575a6aaa8/service/src/metrics/mod.rs#L93). But only `deployment` is set [here](https://github.com/graphops/indexer-service-rs/blob/cf21797abf63d9f0b02cf4af9ac61cc575a6aaa8/service/src/server/routes/subgraphs.rs#L41). I would have just fixed this, but I'm not sure what the `name` label is supposed to be populated with.

**Comment by hopeyen** [comment]
This is weird, ts impl [here](https://github.com/graphprotocol/indexer/blob/a73b7dd41791e2ea44a45f79641939e687434abf/packages/indexer-service/src/server/index.ts#L253) has the 2 labels but only uses deployment. 
I would just remove `name` from the metrics declaration
